dataset:
  data_path: "datasets/CX-Brights"
  class_root_path: "OD_bright/nabrus"
  image_shape: [224, 224, 3]
  noise_dim: 128

model:
  type: "WGAN"

train:
  batch_size: 32
  epochs: 5000
  checkpoint_freq: 20

  generator_lr: 0.0002
  generator_betas: [0.5, 0.9]
  discriminator_lr: 0.0002
  discriminator_betas: [0.5, 0.9]

  image_visual_frequency: 20
  image_visual_num: 5

  train_log_root: "outputs"
  train_checkpoints: "checkpoints"
  tensorboard_root: "tensorboard_logs"

